import type { User, Post, Reply, Category } from './types';

export const CURRENT_USER_ID = 'user-1';

export const MOCK_USERS: User[] = [
  { id: 'user-1', name: 'Alex Rivera', initials: 'AR', avatarColor: '#2563eb', points: 320, bio: 'Full-stack developer passionate about teaching and learning.', joinDate: '2024-09-01', postCount: 8, replyCount: 24, helpfulCount: 11, activeCourses: [{ id: 'c1', name: 'Advanced Frontend', module: 'Module 4: Animation', icon: '<>' }, { id: 'c2', name: 'Node.js Essentials', module: 'Module 2: APIs', icon: '⚙' }], badges: [{ id: 'b1', name: 'First Post', emoji: '✏️', description: 'Created your first discussion' }, { id: 'b2', name: 'Helpful', emoji: '🤝', description: 'Received 10 upvotes on replies' }] },
  { id: 'user-2', name: 'Sarah J.', initials: 'SJ', avatarColor: '#7c3aed', points: 540, bio: 'UI/UX designer transitioning into frontend dev.', joinDate: '2024-07-15', postCount: 15, replyCount: 42, helpfulCount: 28, activeCourses: [{ id: 'c1', name: 'Advanced Frontend', module: 'Module 4: Animation', icon: '<>' }, { id: 'c3', name: 'UX Foundations', module: 'Module 2: Wireframing', icon: '✂' }], badges: [{ id: 'b1', name: 'First Post', emoji: '✏️', description: 'Created your first discussion' }, { id: 'b3', name: 'Top Contributor', emoji: '🏆', description: 'Ranked in top 10 contributors' }, { id: 'b4', name: 'Problem Solver', emoji: '🔧', description: '5 answers accepted as resolved' }] },
  { id: 'user-3', name: 'Marcus T.', initials: 'MT', avatarColor: '#059669', points: 850, bio: 'Senior React developer. I love helping others debug.', joinDate: '2024-03-20', postCount: 22, replyCount: 97, helpfulCount: 64, activeCourses: [{ id: 'c4', name: 'React Mastery', module: 'Module 6: Performance', icon: '⚛' }], badges: [{ id: 'b3', name: 'Top Contributor', emoji: '🏆', description: 'Ranked in top 10 contributors' }, { id: 'b4', name: 'Problem Solver', emoji: '🔧', description: '5 answers accepted as resolved' }, { id: 'b5', name: 'Mentor', emoji: '🎓', description: 'Helped 20+ learners resolve issues' }, { id: 'b6', name: 'Deep Diver', emoji: '🏊', description: 'Posted 20+ detailed replies' }] },
  { id: 'user-4', name: 'Elena L.', initials: 'EL', avatarColor: '#dc2626', points: 1200, bio: 'Lead instructor at OmniLearn. Accessibility advocate.', joinDate: '2023-11-01', postCount: 38, replyCount: 143, helpfulCount: 112, activeCourses: [{ id: 'c5', name: 'Accessibility First', module: 'Module 1: Foundations', icon: '♿' }, { id: 'c3', name: 'UX Foundations', module: 'Module 5: Testing', icon: '✂' }], badges: [{ id: 'b3', name: 'Top Contributor', emoji: '🏆', description: 'Ranked in top 10 contributors' }, { id: 'b5', name: 'Mentor', emoji: '🎓', description: 'Helped 20+ learners resolve issues' }, { id: 'b7', name: 'OmniLearn Staff', emoji: '⭐', description: 'Official OmniLearn team member' }, { id: 'b8', name: 'Legend', emoji: '🌟', description: 'Reached 1000+ points' }] },
  { id: 'user-5', name: 'Jane D.', initials: 'JD', avatarColor: '#d97706', points: 1200, bio: 'Backend engineer exploring frontend. TS enthusiast.', joinDate: '2024-01-10', postCount: 19, replyCount: 88, helpfulCount: 71, activeCourses: [{ id: 'c6', name: 'TypeScript Deep Dive', module: 'Module 3: Generics', icon: 'TS' }], badges: [{ id: 'b3', name: 'Top Contributor', emoji: '🏆', description: 'Ranked in top 10 contributors' }, { id: 'b8', name: 'Legend', emoji: '🌟', description: 'Reached 1000+ points' }, { id: 'b4', name: 'Problem Solver', emoji: '🔧', description: '5 answers accepted as resolved' }] },
  { id: 'user-6', name: 'Mark K.', initials: 'MK', avatarColor: '#0891b2', points: 850, bio: 'DevOps background pivoting to fullstack.', joinDate: '2024-02-14', postCount: 13, replyCount: 61, helpfulCount: 45, activeCourses: [{ id: 'c7', name: 'Cloud Architecture', module: 'Module 4: Serverless', icon: '☁' }, { id: 'c1', name: 'Advanced Frontend', module: 'Module 1: Intro', icon: '<>' }], badges: [{ id: 'b3', name: 'Top Contributor', emoji: '🏆', description: 'Ranked in top 10 contributors' }, { id: 'b6', name: 'Deep Diver', emoji: '🏊', description: 'Posted 20+ detailed replies' }] },
  { id: 'user-7', name: 'Alex R.', initials: 'AR', avatarColor: '#be185d', points: 620, bio: 'Computer science student. Love algorithms and UI.', joinDate: '2024-08-05', postCount: 11, replyCount: 34, helpfulCount: 19, activeCourses: [{ id: 'c8', name: 'Data Structures', module: 'Module 5: Trees', icon: '🌲' }, { id: 'c1', name: 'Advanced Frontend', module: 'Module 3: State', icon: '<>' }], badges: [{ id: 'b1', name: 'First Post', emoji: '✏️', description: 'Created your first discussion' }, { id: 'b2', name: 'Helpful', emoji: '🤝', description: 'Received 10 upvotes on replies' }] },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-css', name: 'CSS & Animations', icon: '🎨', color: 'text-purple-700', bgColor: 'bg-purple-50', borderColor: 'border-purple-200', description: 'Styling, animations, transitions, and layout techniques.' },
  { id: 'cat-react', name: 'React', icon: '⚛️', color: 'text-cyan-700', bgColor: 'bg-cyan-50', borderColor: 'border-cyan-200', description: 'Components, hooks, state management, and React ecosystem.' },
  { id: 'cat-js', name: 'JavaScript', icon: '🟨', color: 'text-yellow-700', bgColor: 'bg-yellow-50', borderColor: 'border-yellow-200', description: 'Core JS concepts, ES6+, async patterns, and browser APIs.' },
  { id: 'cat-ts', name: 'TypeScript', icon: '🔷', color: 'text-blue-700', bgColor: 'bg-blue-50', borderColor: 'border-blue-200', description: 'Types, generics, interfaces, and TypeScript best practices.' },
  { id: 'cat-ux', name: 'UX & Design', icon: '✏️', color: 'text-pink-700', bgColor: 'bg-pink-50', borderColor: 'border-pink-200', description: 'User experience, wireframing, accessibility, and visual design.' },
  { id: 'cat-backend', name: 'Backend & APIs', icon: '⚙️', color: 'text-green-700', bgColor: 'bg-green-50', borderColor: 'border-green-200', description: 'Node.js, REST APIs, databases, and server-side patterns.' },
  { id: 'cat-general', name: 'General', icon: '💬', color: 'text-slate-700', bgColor: 'bg-slate-50', borderColor: 'border-slate-200', description: 'Off-topic discussions, career advice, and introductions.' },
  { id: 'cat-announce', name: 'Announcements', icon: '📢', color: 'text-teal-700', bgColor: 'bg-teal-50', borderColor: 'border-teal-200', description: 'Official OmniLearn announcements, workshops, and events.' },
];

export const MOCK_POSTS: Post[] = [
  { id: 'post-1', title: 'How do I implement custom easing in the CSS Animation module?', content: "I'm currently working through Chapter 4 of the Advanced Frontend course...", authorId: 'user-2', categoryId: 'cat-css', tags: ['css-animations', 'cubic-bezier', 'keyframes', 'advanced-frontend'], status: 'unanswered', upvotes: 12, upvotedBy: ['user-3', 'user-5', 'user-6'], views: 42, createdAt: '2026-06-18T10:00:00Z', isPinned: false, bookmarkedBy: ['user-3'], courseId: 'c1' },
  { id: 'post-2', title: 'Best practices for structuring large React applications', content: "After finishing the React fundamentals path, I'm starting a personal project...", authorId: 'user-3', categoryId: 'cat-react', tags: ['react', 'architecture', 'folder-structure', 'scalability'], status: 'resolved', upvotes: 47, upvotedBy: ['user-1', 'user-2', 'user-4', 'user-5', 'user-6', 'user-7'], views: 340, createdAt: '2026-06-17T14:00:00Z', isPinned: false, bookmarkedBy: ['user-1', 'user-2', 'user-7'] },
  { id: 'post-3', title: 'Upcoming Workshop: Accessibility First Design', content: "Join us next Thursday for a deep dive into WCAG guidelines...", authorId: 'user-4', categoryId: 'cat-announce', tags: ['workshop', 'accessibility', 'wcag', 'event'], status: 'announcement', upvotes: 31, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-5'], views: 120, createdAt: '2026-06-15T09:00:00Z', isPinned: true, bookmarkedBy: ['user-1', 'user-2', 'user-3', 'user-5', 'user-6'] },
  { id: 'post-4', title: "TypeScript generics — when to use them vs. just using `any`?", content: "I keep seeing generics in every TypeScript codebase...", authorId: 'user-7', categoryId: 'cat-ts', tags: ['typescript', 'generics', 'types', 'beginner'], status: 'resolved', upvotes: 29, upvotedBy: ['user-2', 'user-3', 'user-5'], views: 215, createdAt: '2026-06-16T11:30:00Z', isPinned: false, bookmarkedBy: ['user-2', 'user-7'], courseId: 'c6' },
  { id: 'post-5', title: 'React useEffect cleanup — what happens if I skip it?', content: "I've been told that useEffect should return a cleanup function...", authorId: 'user-1', categoryId: 'cat-react', tags: ['react', 'useeffect', 'memory-leaks', 'hooks'], status: 'unanswered', upvotes: 18, upvotedBy: ['user-2', 'user-6'], views: 87, createdAt: '2026-06-18T08:00:00Z', isPinned: false, bookmarkedBy: [] },
  { id: 'post-6', title: 'What is the difference between async/await and Promises?', content: "I'm confused about when to use async/await vs .then()/.catch()...", authorId: 'user-7', categoryId: 'cat-js', tags: ['javascript', 'async', 'promises', 'es6'], status: 'resolved', upvotes: 34, upvotedBy: ['user-1', 'user-3', 'user-4', 'user-5'], views: 410, createdAt: '2026-06-14T16:00:00Z', isPinned: false, bookmarkedBy: ['user-1', 'user-7'] },
  { id: 'post-7', title: 'Node.js API rate limiting — best library to use?', content: "I'm building a REST API with Express and need to add rate limiting...", authorId: 'user-6', categoryId: 'cat-backend', tags: ['nodejs', 'express', 'rate-limiting', 'api'], status: 'unanswered', upvotes: 9, upvotedBy: ['user-2'], views: 54, createdAt: '2026-06-18T06:00:00Z', isPinned: false, bookmarkedBy: [] },
  { id: 'post-8', title: 'New Course Drop: Advanced CSS Grid & Subgrid', content: "We're thrilled to announce the launch of our newest course module...", authorId: 'user-4', categoryId: 'cat-announce', tags: ['announcement', 'css-grid', 'new-course', 'subgrid'], status: 'announcement', upvotes: 54, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-5', 'user-6', 'user-7'], views: 289, createdAt: '2026-06-13T12:00:00Z', isPinned: true, bookmarkedBy: ['user-1', 'user-2', 'user-3', 'user-6'] },
  { id: 'post-9', title: 'Should I learn Vue or stick with React for job market?', content: "I've been learning React through OmniLearn and love it...", authorId: 'user-1', categoryId: 'cat-general', tags: ['career', 'react', 'vue', 'job-market'], status: 'discussion', upvotes: 22, upvotedBy: ['user-3', 'user-5', 'user-7'], views: 178, createdAt: '2026-06-16T19:00:00Z', isPinned: false, bookmarkedBy: ['user-7'] },
  { id: 'post-10', title: 'CSS specificity wars — how to keep styles maintainable?', content: "My codebase has become a nightmare of !important declarations...", authorId: 'user-2', categoryId: 'cat-css', tags: ['css', 'specificity', 'css-modules', 'refactoring'], status: 'resolved', upvotes: 25, upvotedBy: ['user-3', 'user-4', 'user-6'], views: 193, createdAt: '2026-06-12T10:00:00Z', isPinned: false, bookmarkedBy: ['user-2'] },
  { id: 'post-11', title: 'How do I test async Redux thunks with Jest?', content: "I've been struggling to write meaningful tests for my Redux thunks...", authorId: 'user-6', categoryId: 'cat-react', tags: ['redux', 'testing', 'jest', 'async-thunk'], status: 'unanswered', upvotes: 7, upvotedBy: ['user-1'], views: 31, createdAt: '2026-06-17T20:00:00Z', isPinned: false, bookmarkedBy: [] },
  { id: 'post-12', title: 'Introducing myself — front-end dev from Lagos 👋', content: 'Hey OmniLearn community! My name is Kofi...', authorId: 'user-7', categoryId: 'cat-general', tags: ['introduction', 'community', 'study-group'], status: 'discussion', upvotes: 41, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5'], views: 95, createdAt: '2026-06-11T08:00:00Z', isPinned: false, bookmarkedBy: [] },
];

export const MOCK_REPLIES: Reply[] = [
  { id: 'reply-1', postId: 'post-2', authorId: 'user-5', content: "Great question! I've built several large React apps...", upvotes: 23, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-7'], isAccepted: true, createdAt: '2026-06-17T15:30:00Z' },
  { id: 'reply-2', postId: 'post-2', authorId: 'user-4', content: "Adding onto Jane's excellent answer...", upvotes: 17, upvotedBy: ['user-1', 'user-3'], isAccepted: false, createdAt: '2026-06-17T16:00:00Z' },
  { id: 'reply-3', postId: 'post-2', authorId: 'user-3', content: "I'd also suggest checking out Bulletproof React repo on GitHub...", upvotes: 11, upvotedBy: ['user-2', 'user-7'], isAccepted: false, createdAt: '2026-06-17T17:00:00Z' },
  { id: 'reply-4', postId: 'post-4', authorId: 'user-5', content: "The difference is type safety that flows through...", upvotes: 31, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-6', 'user-7'], isAccepted: true, createdAt: '2026-06-16T12:30:00Z' },
  { id: 'reply-5', postId: 'post-4', authorId: 'user-3', content: "One practical rule of thumb: reach for generics when...", upvotes: 18, upvotedBy: ['user-2', 'user-7'], isAccepted: false, createdAt: '2026-06-16T13:00:00Z' },
  { id: 'reply-6', postId: 'post-6', authorId: 'user-3', content: "They compile to the same thing under the hood...", upvotes: 29, upvotedBy: ['user-1', 'user-2', 'user-5', 'user-7'], isAccepted: true, createdAt: '2026-06-14T16:45:00Z' },
  { id: 'reply-7', postId: 'post-10', authorId: 'user-4', content: "The !important spiral is one of the most common CSS anti-patterns...", upvotes: 21, upvotedBy: ['user-2', 'user-3', 'user-6'], isAccepted: true, createdAt: '2026-06-12T11:30:00Z' },
  { id: 'reply-8', postId: 'post-10', authorId: 'user-3', content: "If you're open to a tooling change, CSS Modules + Tailwind...", upvotes: 12, upvotedBy: ['user-2', 'user-5'], isAccepted: false, createdAt: '2026-06-12T12:00:00Z' },
  { id: 'reply-9', postId: 'post-9', authorId: 'user-3', content: "Go deeper on React. The job market reality...", upvotes: 19, upvotedBy: ['user-1', 'user-5', 'user-7'], isAccepted: false, createdAt: '2026-06-16T19:30:00Z' },
  { id: 'reply-10', postId: 'post-9', authorId: 'user-5', content: "Counterpoint: if a specific job you want lists Vue...", upvotes: 15, upvotedBy: ['user-3', 'user-7'], isAccepted: false, createdAt: '2026-06-16T20:00:00Z' },
  { id: 'reply-11', postId: 'post-12', authorId: 'user-4', content: "Welcome to the community, Kofi! 🎉", upvotes: 14, upvotedBy: ['user-1', 'user-2', 'user-3', 'user-7'], isAccepted: false, createdAt: '2026-06-11T09:00:00Z' },
  { id: 'reply-12', postId: 'post-12', authorId: 'user-1', content: "Hey Kofi! Welcome! I'm on Module 3 too...", upvotes: 8, upvotedBy: ['user-7'], isAccepted: false, createdAt: '2026-06-11T10:00:00Z' },
  { id: 'reply-13', postId: 'post-3', authorId: 'user-2', content: "This is so needed! I've been meaning to audit...", upvotes: 6, upvotedBy: ['user-1', 'user-6'], isAccepted: false, createdAt: '2026-06-15T10:00:00Z' },
  { id: 'reply-14', postId: 'post-3', authorId: 'user-4', content: "Yes! The recording will be posted in the course library...", upvotes: 9, upvotedBy: ['user-1', 'user-2', 'user-3'], isAccepted: false, createdAt: '2026-06-15T10:30:00Z' },
];
